name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 ? * 0 *'

jobs:
  test_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: 3.7
            TOXENV: "py37"
          - python-version: 3.8
            TOXENV: "py38"
          - python-version: 3.9
            TOXENV: "py39"
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repo
      - uses: actions/setup-python@v2
        name: Set up Python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt requirements-dev.txt
          pip freeze
      - name: Linter Checks
        run: |
          make lint
      - name: Notebook Tests
        run: |
          make test

  test_macOS:
    runs-on: macOS-latest
    strategy:
      matrix:
        include:
          - python-version: 3.7
            TOXENV: "py37"
          - python-version: 3.8
            TOXENV: "py38"
          - python-version: 3.9
            TOXENV: "py39"
          - python-version: "3.10"
            TOXENV: "py310"
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repo

      - uses: actions/setup-python@v2
        name: Set up Python ${{ matrix.python-version }}

        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt requirements-dev.txt
      - name: Linter Checks
        run: |
          make lint
      - name: Notebook Tests
        run: |
          make test

  test_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - python-version: 3.7
            TOXENV: "py37"
          - python-version: 3.8
            TOXENV: "py38"
          - python-version: 3.9
            TOXENV: "py39"
          - python-version: "3.10"
            TOXENV: "py310"
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repo
      - uses: actions/setup-python@v2
        name: Set up Python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt requirements-dev.txt
      - name: Linter Checks
        run: |
          make lint
      - name: Notebook Tests
        run: |
          make test
