name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  tests_py37:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    needs: []
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run Tests
        run: |
            pip install -U pip --user
            pip install tox
            tox -e py37
        shell: bash
  tests_py38:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    needs: []
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run Tests
        run: |
            pip install -U pip --user
            pip install tox
            tox -e py38
        shell: bash
  tests_py39:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    needs: []
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run Tests
        run: |
            pip install -U pip --user
            pip install tox
            tox -e py39
        shell: bash
  tests_py310:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    needs: []
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python "3.10"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Run Tests
        run: |
            pip install -U pip --user
            pip install tox
            tox -e py310
        shell: bash
