name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  tests:
    runs-on: ${{ matrix.ox }}
    strategy:
      matrix:
        include:
          - python-version: 3.7
            TOXENV: "py37"
          - python-version: 3.8
            TOXENV: "py38"
          - python-version: 3.9
            TOXENV: "py39"
          - python-version: "3.10"
            TOXENV: "py310"
          - os: ubuntu-latest
          - os: macOS-latest
          - os: windows-latest


    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: pip install --upgrade pip tox virtualenv
      - name: Test with tox
        env:
          TOXENV: ${{ matrix.TOXENV }}
        run: tox
