name: Qiskit Development Version Notebook Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Install Dependencies
        run: |
          pip install -U pip
          pip install -r requirements-dev.txt -r requirements.txt \
              git+https://github.com/Qiskit/qiskit-terra.git \
              git+https://github.com/Qiskit/qiskit-aer.git \
              git+https://github.com/Qiskit/qiskit-machine-learning.git
          pip freeze
        shell: bash
      - name: Run Makefile
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: make test
